### ISSUE TITLE
访问时出现 Privacy error 报错

### ISSUE THREAD

**Issue by CyrusYip** [rbind/xiangyun#5]
访问 https://xiangyun.rbind.io/ 的时候会报错，似乎是证书问题。用手机网络和电脑宽带访问都这样。以下是浏览器显示的内容：

Your connection is not private
Attackers might be trying to steal your information from xiangyun.rbind.io (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
This server could not prove that it is xiangyun.rbind.io; its security certificate is from *.netlify.app. This may be caused by a misconfiguration or an attacker intercepting your connection.

Proceed to xiangyun.rbind.io (unsafe)

**Comment by XiangyunHuang** [comment]
我也遇到过，有时候刷新一下又好了，或者关掉代理也能好，根本原因不知道是啥？ @yihui 需要我做些什么去防止这种情况吗？求教

**Comment by yihui** [comment]
https://github.com/rbind/support/issues/797#issuecomment-830434719

**Comment by XiangyunHuang** [comment]
<img width="815" alt="截屏2021-05-20 下午12 50 05" src="https://user-images.githubusercontent.com/12031874/118920968-eafbb080-b969-11eb-9e2b-63d077c4afb7.png">

补充一个截图说明

**Comment by XiangyunHuang** [comment]
<img width="1310" alt="截屏2021-05-20 下午12 58 44" src="https://user-images.githubusercontent.com/12031874/118921657-1e8b0a80-b96b-11eb-9448-e55514a0b9b7.png">

现在好了，访问正常了
